[project]
name = "deepthink"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "joblib>=1.5.1",
    "litellm>=1.74.7",
    "math-verify>=0.8.0",
    "openai>=1.97.1",
    "tqdm-joblib>=0.0.4",
]
